sudo: required
dist: trusty

language: ruby
rvm:
    - 2.4

cache:
  bundler: true
  directories:
  - $TRAVIS_BUILD_DIR/node_modules

before_install:
    - nvm install 8

before_script: "_ci/setup.sh"
script: "_ci/build.sh"
after_success: "_ci/deploy.sh"

# deploy:
#   skip_cleanup: true
#   provider: script
#   script: "_ci/deploy.sh"
#   on:
#     all_branches: true

notifications:
    email: false
