

# The Basics
# --------------------
name:                   BigchainDB
description:            'The scalable blockchain database.'
url:                    https://www.bigchaindb.com

email:
    contact:            contact@bigchaindb.com
    cla:                troy@ascribe.io

twitter:                BigchainDB
facebook:               BigchainDB
github:
    org:                bigchaindb
    repo:               bigchaindb
medium:                 the-bigchaindb-blog
googlegroup:            bigchaindb
gitter:                 bigchaindb/bigchaindb
disqus:                 bigchain

address:
    company:            BigchainDB GmbH
    street:             Wichertstr. 14a
    zip:                10439
    city:               Berlin
    country:            Germany

# Track all the things
# --------------------
analyticsID:            UA-60614729-8


# Urls
# --------------------
permalink:              /blog/:title/
paginate:               15
paginate_path:          "/blog/page/:num"
category_dir:           "/blog/category/"
category_title_prefix:  ""


# Content Parsing
# --------------------
markdown:               redcarpet

kramdown:
    input: GFM
    extensions:
        - autolink
        - footnotes
        - smart

redcarpet:
    extensions:         ['autolink', 'smart', 'hard_wrap', 'with_toc_data']


# Generator
# --------------------
source:                 ./_src
destination:            ./_dist

sass:
    sass_dir: _assets/styles


# Plugins
# --------------------
gems:
    - jekyll-sitemap
    - jekyll-redirect-from
    - jekyll-paginate
    - jekyll-archives


# jekyll-archives
# --------------------
jekyll-archives:
    enabled:
        - categories
    layout: 'archive'
    permalinks:
        category: '/blog/category/:name/'
