

# The Basics
# --------------------
name:                   BigchainDB
description:            'The worldâ€™s most scalable blockchain database.'
url:                    https://www.bigchaindb.com

email:
    contact:            contact@bigchaindb.com
    cla:                troy@ascribe.io

twitter:                BigchainDB
facebook:               BigchainDB
github:                 BigchainDB
medium:                 the-bigchain-blog
disqus:                 bigchain

address:
    street:             Wichertstr. 17
    zip:                10439
    city:               Berlin
    country:            Germany

# Track all the things
# --------------------
analyticsID:            UA-60614729-8


# Urls
# --------------------
permalink:              /:title/


# Content Parsing
# --------------------
markdown:               redcarpet

kramdown:
    input: GFM
    extensions:
        - autolink
        - footnotes
        - smart

redcarpet:
    extensions:         ['autolink', 'smart', 'hard_wrap', 'with_toc_data']


# Generator
# --------------------
source:                 ./_src
destination:            ./_dist


# Plugins
# --------------------
gems:
    - jekyll-sitemap
    - jekyll-redirect-from
